### ISSUE TITLE
ERROR: null value in column "activation_key" violates not-null constrain

### ISSUE THREAD

**Issue by upratathlavu** [cakemanager/cakephp-cakemanager#3] opened 2015-04-03 14:21 UTC
Hi, I'm not sure if this is right place to ask, but I'm getting this error when adding user (via `bin/cake manager user` and `localhost/admin/manager/users/add` too). 

I installed cakemanager following this steps http://cakemanager.org/docs/1.0/installation/ but in place of first step I used `composer require cakemanager/cakephp-cakemanager dev-develop` because I didn't know where to put those `"require":...` lines and saw somewhere else this `composer ...` command. 

I had problem during `bin/cake migrations migrate -p CakeManager` step, when it compalined something about out of range value and resloved it changing `'default' => '0000-00-00 00:00:00'` to `'default' => 'now()'` in initial script. But I think this isn't related.

I see that activation_key in sql query is set to null, so that's the problem, but I'm not sure if this is a bug or if I'm doing something wrong - because I'm new to cakephp and php frameworks as such:

`Error: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "activation_key" violates not-null constraint DETAIL: Failing row contains (10, 1, test@test.sk, 0, null, $2y$10$E8pYONW2ngJAP./I9ZaU9eilN071JfwQbUp5jPsLh0qyDW9U/cpNm, 2015-04-03 14:17:12, 2015-04-03 14:17:12).`

Thanks for help.

**Comment by bobmulder** [comment] 2015-04-03 16:31
Hey Upratathlavu,

Because you saw this as a bug this is the right place. I have everything done like you, and was able to install the CakeManager perfectly. Some questions that may be important
- Wich version of php are you running?
- Wich version of (my)sql are you using?
- What environment are you working (xampp, wamp...) 
- Did you get errors when requiring the CakeManager via composer?

Greetz

Bob

**Comment by upratathlavu** [comment] 2015-04-03 17:58
Hi, thanks:
- php 5.6.5-1
- postgresql 9.4.1-1
- it's Arch linux with apache 2.4.12-2
- if you mean exactly at that step, then, as far as I remember, no, I think I only got errors during installation when migrating db (see my previous post) and when creating user using `bin/cake manager user`. But I had issues with composer - it said it's out of date and I should self-update it, but someghing went wrong and it didn't work afterwards, so I had to --rollback (which too wasn't without problems...); this was before installing cakemanager. Could it be this? Is it needed that composer is up to date before installing cakemanager? Thanks again.

**Comment by upratathlavu** [comment] 2015-04-03 20:31
Yes, sorry, I forgot :) I got an error about dependencies - at first I used `composer require cakemanager/cakephp-cakemanager dev-master` (I don't know why), but it complained about dependencies, so perhaps I found in installation steps it should be dev-develop, and it worked. 

Now I'm trying to start from scratch (after updating composer) and am getting this dependency error:

[upratathlavu@archaik ~/projects 22:15]$ composer require cakemanager/cakephp-cakemanager dev-develop
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cakemanager/cakephp-cakemanager dev-develop -> satisfiable by cakemanager/cakephp-cakemanager[dev-develop].
    - cakemanager/cakephp-cakemanager dev-develop requires cakemanager/cakephp-utils 1.0.*@dev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, deleting ./composer.json.

Which one should I use? dev-develop or dev-master, or? Thanks.

**Comment by bobmulder** [comment] 2015-04-03 21:17
Hey, 

You are using postgresql. While I am not familar with that, I think that's the issue. I will check if that type database is tested or not. Maybe it's a good idea to add some default `.sql` files for users who want to use that...

About the composer error: It's a strange error. Please try to install cake again (all clear), and then the CakeManager. The problem tells about a typo-fix, so that could it be...

**Comment by bobmulder** [comment] 2015-04-03 21:23
Maybe this could be helpful...

http://docs.phinx.org/en/latest/migrations.html#valid-column-options

@upratathlavu I think the composer-problem will be solved if you try again. Because the problem about the query is caused by postgresql and the migrations I suggest you can try to fix it using the url above (move to the datetime-docs). If you got the solution feel free to open up a PR and i'll look if it works on my side. I hope we gen can out of this!

**Comment by bobmulder** [comment] 2015-04-08 21:22
Hey @upratathlavu, didn't hear from you anymore. Have you seen my previous posts? How's the bug? 

Greetz

**Comment by emmio-micke** [comment] 2015-04-09 10:54
I have pretty much the same problem, running php 5.6/mysql 5.6 on vagrant:

```
$ bin/cake manager user

Welcome to CakePHP v3.0.1 Console
---------------------------------------------------------------
App : src
Path: /var/www/inventory/src/
---------------------------------------------------------------

Welcome to CakePHP v3.0.1 Console
---------------------------------------------------------------
App : src
Path: /var/www/inventory/src/
---------------------------------------------------------------
Enter the e-mailaddress
> mikael.olsson@emmio.se
Enter the password
> somepassword
Exception: SQLSTATE[HY000]: General error: 1364 Field 'activation_key' doesn't have a default value in [/var/www/inventory/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 36]
2015-04-09 10:25:28 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'activation_key' doesn't have a default value
Stack Trace:
#0 /var/www/inventory/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 /var/www/inventory/vendor/cakephp/cakephp/src/Database/Connection.php(274): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/inventory/vendor/cakephp/cakephp/src/Database/Query.php(175): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /var/www/inventory/vendor/cakephp/cakephp/src/ORM/Table.php(1516): Cake\Database\Query->execute()
#4 /var/www/inventory/vendor/cakephp/cakephp/src/ORM/Table.php(1436): Cake\ORM\Table->_insert(Object(CakeManager\Model\Entity\User), Array)
#5 /var/www/inventory/vendor/cakephp/cakephp/src/ORM/Table.php(1367): Cake\ORM\Table->_processSave(Object(CakeManager\Model\Entity\User), Object(ArrayObject))
#6 /var/www/inventory/vendor/cakephp/cakephp/src/Database/Connection.php(561): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#7 /var/www/inventory/vendor/cakephp/cakephp/src/ORM/Table.php(1368): Cake\Database\Connection->transactional(Object(Closure))
#8 /var/www/inventory/vendor/cakemanager/cakephp-cakemanager/src/Shell/Task/UserTask.php(52): Cake\ORM\Table->save(Object(CakeManager\Model\Entity\User))
#9 [internal function]: CakeManager\Shell\Task\UserTask->main()
#10 /var/www/inventory/vendor/cakephp/cakephp/src/Console/Shell.php(387): call_user_func_array(Array, Array)
#11 /var/www/inventory/vendor/cakephp/cakephp/src/Console/Shell.php(382): Cake\Console\Shell->runCommand(Array, false)
#12 /var/www/inventory/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(200): Cake\Console\Shell->runCommand(Array, true)
#13 /var/www/inventory/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(171): Cake\Console\ShellDispatcher->_dispatch()
#14 /var/www/inventory/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(122): Cake\Console\ShellDispatcher->dispatch()
#15 /var/www/inventory/bin/cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#16 {main}



[10:25 ]-[vagrant@localhost]-[/var/www/inventory]-[git develop]
$
```

**Comment by bobmulder** [comment] 2015-04-09 10:59
Hey @emmio-micke, I pushed a fix wich contains a default value... Can you try to update the plugin and run the migration again?

**Comment by emmio-micke** [comment] 2015-04-09 11:08
I get a new error now. I deleted the tables, updated my composer.json, ran `composer update` and then tried to install again:

```
[11:03 ]-[vagrant@localhost]-[/var/www/inventory]-[git develop]
$ bin/cake migrations migrate -p CakeManager

Welcome to CakePHP v3.0.1 Console
---------------------------------------------------------------
App : src
Path: /var/www/inventory/src/
---------------------------------------------------------------
using migration path /var/www/inventory/vendor/cakemanager/cakephp-cakemanager/config/Migrations
using environment default
using adapter mysql
using database inventory

 == 20141231074222 Inital: migrating



  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'activation_key'



migrate [-t|--target="..."] [-p|--plugin="..."] [-c|--connection="..."] [-s|--source="..."]
```

**Comment by bobmulder** [comment] 2015-04-09 11:11
My apologies @emmio-micke, the column has to be  a string, not a integer ;). I've commited a fix... Is it working?

**Comment by emmio-micke** [comment] 2015-04-09 11:16
Yes, it seems to work now. :+1: I'm going to check this plugin out now, thanks!

**Comment by bobmulder** [comment] 2015-04-09 11:17
Okay glad to hear. Thanks for letting me know @emmio-micke. Good luck with the plugin ;) Feel free to chat at gitter or mail me.

@upratathlavu after these commits, maybe your problem is solved? Try to migrate your database again... Please let me know if it's working or not ;)

**Comment by upratathlavu** [comment] 2015-04-12 09:15
Hi, thanks for update, but sorry, no time now, hopefully I'll check it in near future.

**Comment by bobmulder** [comment] 2015-05-16 17:12
@upratathlavu Please let me know if your bug is fixed. Else I'll close this issue ;)

Greetz

Bob

**Closed as completed** 2015-05-19 18:23 UTC
Labels: help wanted
